### ISSUE TITLE
implementing pieces ts sdk for local llms

### ISSUE THREAD

**Issue by shivscaler** [andrewnguonly/Lumos#10]
Hi @andrewnguonly can you please try to build another project with https://github.com/pieces-app/client

Pieces allows for using LLMs to also get ChatGPT like Persistent chats that can answer any questions. And it supports using local LLMs. there is a /chats API endpoint. 

The chrome extension is here: https://docs.pieces.app/extensions-plugins/chrome

Can you build a similar project but with LLM running through their Typescript SDK.

**Comment by shivscaler** [comment]
It would be great if it is possible @andrewnguonly

**Comment by andrewnguonly** [comment]
Hi @shivscaler, I don't fully understand what you're asking. Where is the documentation for the Pieces Typescript SDK?

**Comment by shivscaler** [comment]
Hi @andrewnguonly 
This is the Github Repo: https://github.com/pieces-app/client for the TypeScript SDK 
Here's a sample example Application using the SDK: https://github.com/pieces-app/example-ts

**Comment by shivscaler** [comment]
Let me know if you could try to implement this. Would be really nice.

**Comment by andrewnguonly** [comment]
@shivscaler, I'll look into it this week.

**Comment by shivscaler** [comment]
Thanks a lot!

**Comment by shivscaler** [comment]
HI @andrewnguonly did you get a chance to look at this?

**Comment by andrewnguonly** [comment]
@shivscaler not yet, sorry. I'll keep this issue updated on my progress.

**Comment by shivscaler** [comment]
Alright thanks @andrewnguonly 
I really look forward to it.

**Comment by shivscaler** [comment]
Hi @andrewnguonly did you get a chance?

**Comment by andrewnguonly** [comment]
Sorry @shivscaler, at this time, I don't plan on integrating Lumos with Pieces. Thanks for bringing it to my attention though.
