### ISSUE TITLE
Lumos with WSL2

### ISSUE THREAD

**Issue by Adaipix** [andrewnguonly/Lumos#126]
Hi, Andrew,
I install Ollama with **Phi2** LLM model under **WSL2** on Windows (Ubuntu 22.04.3 LTS).
I install **Lumos 1.0.10** under Chrome (latest)
I start the server with the command **OLLAMA_ORIGINS=chrome-extension://* ollama serve**
I type something in Lumos but nothing happens
![Capture d'écran 2024-03-10 151553](https://github.com/andrewnguonly/Lumos/assets/162893141/7a8829f5-0013-4434-9dd6-5d3a1e949993)
![Capture d'écran 2024-03-10 151818](https://github.com/andrewnguonly/Lumos/assets/162893141/9b605fad-ac2e-4caf-8516-577666742d9d)
![Capture d'écran 2024-03-10 151859](https://github.com/andrewnguonly/Lumos/assets/162893141/77efbd5b-80a1-46bd-becb-7ae33e094bcc)
![Capture d'écran 2024-03-10 152209](https://github.com/andrewnguonly/Lumos/assets/162893141/b182d691-95a6-4429-a6c9-069adc8c8be0)

**Comment by andrewnguonly** [comment]
This might be the same issue: https://github.com/ollama/ollama/issues/2736

@Adaipix, can you follow this instruction to confirm? https://github.com/ollama/ollama/issues/2736#issuecomment-1962848427

**Comment by Adaipix** [comment]
> This might be the same issue: [ollama/ollama#2736](https://github.com/ollama/ollama/issues/2736)
> 
> @Adaipix, can you follow this instruction to confirm? [ollama/ollama#2736 (comment)](https://github.com/ollama/ollama/issues/2736#issuecomment-1962848427)

@andrewnguonly It works on PowerShell but nothing happens in Lumos.
![Capture d'écran 2024-03-10 170351](https://github.com/andrewnguonly/Lumos/assets/162893141/17bbbfb9-7213-4056-9b97-f05440c204c4)

**Comment by Adaipix** [comment]
@andrewnguonly I found the solution by editing the "background.js" file and replacing the occurrences "llama2" with "phi", my model.

**Comment by andrewnguonly** [comment]
> @andrewnguonly I found the solution by editing the "background.js" file and replacing the occurrences "llama2" with "phi", my model. But it's extremely slow compared to ollama CLI !

Ok. There might be a bug with retrieving the Lumos options. I need to investigate more. I assume you don't have the `llama2` model downloaded at all. I can start from here. If there's any other information you can share about your setup, that would be great!

I'll investigate the "slowness" with `phi` separately.

**Comment by andrewnguonly** [comment]
I found the bug and it's fixed in this PR: https://github.com/andrewnguonly/Lumos/pull/127

I'll merge this change ASAP and cut a new release (`1.0.11`).

**Comment by PhPv** [comment]
Hi. I ran into the same problem when I tried to walk through the quickstart from llamindex. Crashes with the error that the api endpoint/chat url was not found http://localhost:11434/api/chat it also says that 404 is not found. What am I doing wrong?

**Comment by andrewnguonly** [comment]
@PhPv, which version of Lumos do you have installed and which Ollama model do you have downloaded?

The 404 error occurs if a model is not downloaded.
