### ISSUE TITLE
Chat with PDF file in browser?

### ISSUE THREAD

**Issue by NeverOccurs** [andrewnguonly/Lumos#131]
Can it do QA based on PDF files opened in Chrome browser?

**Comment by andrewnguonly** [comment]
This functionality is not supported now, but I'll definitely consider adding it.

I'm not sure how this would be implemented from a technical standpoint. I need to do some research. Ideally, a solution would support any file type that can be opened by a browser (pdf, docx, etc).

**Comment by andrewnguonly** [comment]
I'll keep this issue open so I know to work on it.

**Comment by andrewnguonly** [comment]
Workaround: PDFs can be uploaded to Lumos, and "chatting" with the PDF will work as if the PDF were on the current web page.

I'll close this issue for now. I don't foresee supporting parsing PDFs directly from the browser in the near future. Browsers render PDFs with special applications, which makes retrieval of the content difficult from a Chrome extension.
