### ISSUE TITLE
Support for Domain Matching (e.g., domain.com matches news.domain.com)

### ISSUE THREAD

**Issue by lesca** [andrewnguonly/Lumos#185]
Hello,

I was wondering if it would be possible to add support for domain matching in the project. Specifically, it would be helpful if a domain like `domain.com` could match its subdomains, such as `news.domain.com`or `location.news.domain.com`.

My test rules indicate the domain name must exactly match. 

This feature would be particularly useful in scenarios where a website has multiple subdomains but html structure is similar. 

Is this a feature already be there but I missed? Or is it possible that could be considered for a future update?

Thank you for your time and consideration!

**Comment by andrewnguonly** [comment]
There's a bug in the domain matching logic. I'll fix it so that subdomains are matched.

**Comment by andrewnguonly** [comment]
Fixed in the latest release (`1.0.16`): https://github.com/andrewnguonly/Lumos/releases/tag/1.0.16
