### ISSUE TITLE
Hotkeys for Windows PC

### ISSUE THREAD

**Issue by ColumbusAI** [andrewnguonly/Lumos#188]
How can I modify the hotkeys e.g. 'cmd + b' that are for Mac to a Windows PC?

**Comment by andrewnguonly** [comment]
Thanks for raising this issue @ColumbusAI. I created a PR to check the `alt` key in the case for Windows PC: https://github.com/andrewnguonly/Lumos/pull/189.

I don't actually have a Windows PC to test this with. Are you able to pull my branch and verify the changes?

**Comment by ColumbusAI** [comment]
yes absolutely! will do and report back shortly

**Comment by ColumbusAI** [comment]
ran into a couple of errors loading unpacked, first being the __tests__ folder I renamed to tests removing underscores and that seemed to solve that but then the background.js is missing and couldn't find in the source?

![tests](https://github.com/user-attachments/assets/445982b3-8159-4fe9-81aa-5d61b176e720)
![background](https://github.com/user-attachments/assets/c9a7d48f-7773-4b11-9899-4850e8a485ff)

**Comment by andrewnguonly** [comment]
@ColumbusAI, can you try this:
1. Run the command `npm run build` to build the extension. You'll need to have `npm` installed.
1. A new `dist` folder will be created.
1. Select the `dist` folder instead of the root `Lumos` directory when loading the extension.

**Comment by ColumbusAI** [comment]
works perfectly! I tried all hotkey combinations that call for the alt vs cmd and they worked. 👍 

Thinking about hotkeys here...could you please add a tooltip or some other visual indicator that can call out the various hotkeys that are available when the Lumos window is open?

currently I need to have the lumos repo open to recall the hotkeys and having a help menu or such integrated into the workflow would help to drive adoption of hotkeys for usability 

![Screenshot 2024-08-25 123007](https://github.com/user-attachments/assets/28845d6b-60ef-46d5-8b72-e2cac467ec28)

**Comment by andrewnguonly** [comment]
> Thinking about hotkeys here...could you please add a tooltip or some other visual indicator that can call out the various hotkeys that are available when the Lumos window is open?

Fair feedback. I originally had tool tips for each button, but I felt like they were crowding the UI. I can bring them back and see how it feels. I'll do this as part of the open PR.

**Comment by ColumbusAI** [comment]
thank you!!

> > Thinking about hotkeys here...could you please add a tooltip or some other visual indicator that can call out the various hotkeys that are available when the Lumos window is open?
> 
> Fair feedback. I originally had tool tips for each button, but I felt like they were crowding the UI. I can bring them back and see how it feels. I'll do this as part of the open PR.
