### ISSUE TITLE
Allow sending only selected visible text on a web page to the Ollama server

### ISSUE THREAD

**Issue by nausher** [andrewnguonly/Lumos#58]
This is a feature request. Since sending the entire page is quite time consuming, can the extension allow for sending only the selected portion of a web page to Ollama. 

This will be especially helpful with processing documents such as Google docs, as well as large web pages.

**Comment by andrewnguonly** [comment]
There are a couple of options here.
1. You can [configure a parser for a specific domain](https://github.com/andrewnguonly/Lumos?tab=readme-ov-file#content-parser-config). For example, you may want to configure a parser for a website that you visit frequently. You can limit the amount of content sent to Ollama by constraining the parsing queries.
1. You can [highlight specific text](https://github.com/andrewnguonly/Lumos?tab=readme-ov-file#highlighted-content) to send in the prompt to Ollama for ad-hoc search use cases. For example, this may be helpful for websites that you don't visit frequently.

What else did you have in mind?

**Comment by andrewnguonly** [comment]
@nausher, closing this issue for now. Please re-open if you have another suggestion for how content can be parsed from the page.
