### ISSUE TITLE
Implement Ollama `keepAlive` parameter for API requests

### ISSUE THREAD

**Issue by andrewnguonly** [andrewnguonly/Lumos#63]
https://github.com/ollama/ollama/blob/v0.1.23/api/types.go#L45

Note: This may be dependent on LangChain changes.

**Comment by ighoshsubho** [comment]
I can Integrate the langchiain client and work on this.

**Comment by andrewnguonly** [comment]
Thanks @ighoshsubho! I opened an issue in the LangChainJS repo here: https://github.com/langchain-ai/langchainjs/issues/4282

**Comment by ighoshsubho** [comment]
Cool
