### ISSUE TITLE
Make the popover longer (?)

### ISSUE THREAD

**Issue by marcelinollano** [andrewnguonly/Lumos#69]
This is more a suggestion, I feel like the popover (or popup in Arc) is a bit short.
Maybe make it at least resizable?

In this example I can barely see the conversation:

![Screen Shot 2024-02-05 at 16 26 59@2x](https://github.com/andrewnguonly/Lumos/assets/6335/938bb1b4-e76f-4728-ae43-07f2edcec36a)

Thank you,

**Comment by andrewnguonly** [comment]
@marcelinollano, I've added a feature to increase the height of the popup window. It's released in version `1.0.5`. Note: Chrome extension popups have a max height of 600px.

**Comment by marcelinollano** [comment]
Awesome! Thank you!
