### ISSUE TITLE
"Connection" indicator 

### ISSUE THREAD

**Issue by sublimator** [andrewnguonly/Lumos#76]
Played with this again, did a git reset hard to origin to update (a bit mindlessly, oops), then of course it overwrote DEFAULT_MODEL (Oh, I see there's a gui for that now in options)

An indicator somewhere for:
Is Ollama alive? 
Needs starting? Responding at all ?
Is model available ( I guess on the fly model config is a whole other issue)
Needs origins configuring ? 403 (or whatever) Forbidden responses?
I guess you could use the browser action icon even. 

The thing is it just seems to quietly go about doing nothing when ollama is not running. 

![image](https://github.com/andrewnguonly/Lumos/assets/525211/8f7fe2e8-5030-41f3-9eaf-1a2e346ad3e1)

<img width="642" alt="image" src="https://github.com/andrewnguonly/Lumos/assets/525211/4fbb95b8-47f2-4477-839f-3401e1f918a1">

re: models 
<img width="601" alt="image" src="https://github.com/andrewnguonly/Lumos/assets/525211/e4df4db4-701d-4567-8eaf-02a8cc042938">

I have various quants of the same model, dunno how often people would actually??? but yeah, I guess if there is maybe should it show tag as discriminator?!

**Comment by andrewnguonly** [comment]
All good feedback. There are some quick enhancements that can be made 👍
