### ISSUE TITLE
Allow usage from `chrome://` URL

### ISSUE THREAD

**Issue by andrewnguonly** [andrewnguonly/Lumos#80]
![image](https://github.com/andrewnguonly/Lumos/assets/7654246/4f460758-4175-4d4c-ba26-b8f89a4c29bc)

**Comment by sublimator** [comment]
Not sure what you're doing but you can list things you want "allowed" in web_accessible_resources in the manifest

**Comment by andrewnguonly** [comment]
I just wanted to be able to use the extension from the `chrome://extensions` tab. The app was breaking because it couldn't perform the script injection.

![image](https://github.com/andrewnguonly/Lumos/assets/7654246/ed97c275-2a12-4425-884b-43b90cd1bc87)
