### ISSUE TITLE
Consider making usage of "Tools" a config option

### ISSUE THREAD

**Issue by moppman** [andrewnguonly/Lumos#98]
The idea of using LangChain Tools for special operations is pretty cool, as is your `Calculator` implementation.

However, using LLMs to automatically classify prompts seems to be pretty fragile, because I'm seeing quite a lot of false positive prompt classifications over several models like Llama2, Mistral and also Gemma.

The models often wrongly classify highlighted code passages as arithmetic expressions, also questions concerning logic and formal languages (e.g. "What's the difference between first order logic and higher order logic?").

So I was wondering if you would consider guarding the `classifyPrompt` code paths with a config option by maybe expanding the `classifyPrompt` condition to something like `toolsEnabled && classifyPrompt`, where `toolsEnabled` could be another checkbox next to "Disable content parsing" or a box in the Lumos options.

Thanks, and take care!

**Comment by andrewnguonly** [comment]
Fair points. I previously considered making tools optional. Here are some other thoughts and ideas:
- Tools can be enabled/disabled on an individual basis.
- Prefix triggers can be customized and can be configured as the only method for executing a tool. Basically, tool execution is configured on the classification method (trigger or LLM response).
- To reduce false positives, specifically for the calculator tool, add extra manual validation to confirm that at least 2 operators (i.e. numbers) and at least 1 operand exist in the prompt.

Any thoughts on the above points?
